<?php

namespace ContainerCObWVB1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DDeZmTfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dDeZmTf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dDeZmTf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ActiviteController::delete' => ['privates', '.service_locator.OctoH5o', 'get_ServiceLocator_OctoH5oService', true],
            'App\\Controller\\ActiviteController::edit' => ['privates', '.service_locator.OctoH5o', 'get_ServiceLocator_OctoH5oService', true],
            'App\\Controller\\ActiviteController::index' => ['privates', '.service_locator.h..bsSR', 'get_ServiceLocator_H__BsSRService', true],
            'App\\Controller\\ActiviteController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ActiviteController::show' => ['privates', '.service_locator.DX5IRBd', 'get_ServiceLocator_DX5IRBdService', true],
            'App\\Controller\\StaffController::delete' => ['privates', '.service_locator.8D0GUWz', 'get_ServiceLocator_8D0GUWzService', true],
            'App\\Controller\\StaffController::edit' => ['privates', '.service_locator.8D0GUWz', 'get_ServiceLocator_8D0GUWzService', true],
            'App\\Controller\\StaffController::index' => ['privates', '.service_locator.oI.7Cm2', 'get_ServiceLocator_OI_7Cm2Service', true],
            'App\\Controller\\StaffController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\StaffController::show' => ['privates', '.service_locator.Iowt0uw', 'get_ServiceLocator_Iowt0uwService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\ActiviteController:delete' => ['privates', '.service_locator.OctoH5o', 'get_ServiceLocator_OctoH5oService', true],
            'App\\Controller\\ActiviteController:edit' => ['privates', '.service_locator.OctoH5o', 'get_ServiceLocator_OctoH5oService', true],
            'App\\Controller\\ActiviteController:index' => ['privates', '.service_locator.h..bsSR', 'get_ServiceLocator_H__BsSRService', true],
            'App\\Controller\\ActiviteController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\ActiviteController:show' => ['privates', '.service_locator.DX5IRBd', 'get_ServiceLocator_DX5IRBdService', true],
            'App\\Controller\\StaffController:delete' => ['privates', '.service_locator.8D0GUWz', 'get_ServiceLocator_8D0GUWzService', true],
            'App\\Controller\\StaffController:edit' => ['privates', '.service_locator.8D0GUWz', 'get_ServiceLocator_8D0GUWzService', true],
            'App\\Controller\\StaffController:index' => ['privates', '.service_locator.oI.7Cm2', 'get_ServiceLocator_OI_7Cm2Service', true],
            'App\\Controller\\StaffController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\StaffController:show' => ['privates', '.service_locator.Iowt0uw', 'get_ServiceLocator_Iowt0uwService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\ActiviteController::delete' => '?',
            'App\\Controller\\ActiviteController::edit' => '?',
            'App\\Controller\\ActiviteController::index' => '?',
            'App\\Controller\\ActiviteController::new' => '?',
            'App\\Controller\\ActiviteController::show' => '?',
            'App\\Controller\\StaffController::delete' => '?',
            'App\\Controller\\StaffController::edit' => '?',
            'App\\Controller\\StaffController::index' => '?',
            'App\\Controller\\StaffController::new' => '?',
            'App\\Controller\\StaffController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ActiviteController:delete' => '?',
            'App\\Controller\\ActiviteController:edit' => '?',
            'App\\Controller\\ActiviteController:index' => '?',
            'App\\Controller\\ActiviteController:new' => '?',
            'App\\Controller\\ActiviteController:show' => '?',
            'App\\Controller\\StaffController:delete' => '?',
            'App\\Controller\\StaffController:edit' => '?',
            'App\\Controller\\StaffController:index' => '?',
            'App\\Controller\\StaffController:new' => '?',
            'App\\Controller\\StaffController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
