<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY5jhHEN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY5jhHEN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY5jhHEN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY5jhHEN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY5jhHEN\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y5jhHEN',
    'container.build_id' => '3079ecd1',
    'container.build_time' => 1708078683,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY5jhHEN');
